openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-custom-traditional-deployer
components:
  schemas:
    variables:
      required:
      - artifact
      - target
      type: object
      properties:
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.
          default: {}
          nullable: true
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            hidden: true
            order: 1
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          default: {}
          nullable: true
          properties:
            runtime_source:
              description: | 
                Specify the runtime source for deploying.
                The runtime source is a collection of script files, which implements the courier's interface.
                More details, please refer to https://registry.terraform.io/providers/seal-io/courier/latest/docs/data-sources/runtime#source.
              title: Runtime Source
              type: string
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 2
        deployment:
          title: Deployment
          type: object
          description: |
            Specify the deployment action, like scheduling, progress time and so on.
          default:
            timeout: 300
            rolling:
              max_surge: 0.25
          nullable: true
          properties:
            rolling:
              nullable: true
              properties:
                max_surge:
                  description: |
                    The maximum percent of targets to deploy at once. The value must be range between 0 to 1.
                  default: 0.25
                  nullable: true
                  minimum: 0.1
                  maximum: 1
                  title: Max Surge
                  type: number
              title: Rolling
              type: object
              x-walrus-ui:
                colSpan: 12
                order: 2
            timeout:
              description: | 
                Specify the maximum time in seconds for a deployment to make progress before it is considered to be failed.
              default: 300
              nullable: true
              title: Timeout
              type: number
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 3
        target:
          title: Target
          type: object
          description: |
            Specify the target of deployment, include the address list of target, authentication information and so on.
          required:
          - addresses
          - authn
          properties:
            addresses:
              description: | 
                Specify the address list of target, which must be reachable.
              items:
                type: string
              title: Addresses
              type: array
              x-walrus-ui:
                colSpan: 12
                order: 1
            authn:
              properties:
                mode:
                  description: |
                    Specify the authentication mode for connecting to target, select from ssh or winrm.
                  default: ssh
                  title: Mode
                  type: string
                  enum:
                  - ssh
                  - winrm
                  x-walrus-ui:
                    order: 1
                secret:
                  description: |
                    Specify the secret for connecting to target, either password or private key.
                  title: Secret
                  type: string
                  format: password
                  writeOnly: true
                  x-walrus-ui:
                    order: 3
                    widget: TextArea
                user:
                  description: |
                    Specify the user for connecting to target.
                  title: User
                  type: string
                  x-walrus-ui:
                    order: 2
              required:
              - mode
              - secret
              - user
              title: Authn
              type: object
              x-walrus-ui:
                colSpan: 12
                order: 3
            insecure:
              description: |
                Specify whether to skip TLS/Hostname verification when connecting to target.
              default: false
              nullable: true
              title: Insecure
              type: boolean
              x-walrus-ui:
                order: 2
            proxies:
              description: |
                Configure bastion hosts or http proxies here.
              nullable: true
              items:
                properties:
                  address:
                    description: |
                      Specify the address of proxy, which must be reachable.
                    title: Address
                    type: string
                    x-walrus-ui:
                      order: 1
                  authn:
                    description: |
                      Specify the authentication information for connecting to proxy.
                    properties:
                      mode:
                        description: |
                          Specify the authentication mode for connecting to proxy, select from proxy or ssh.
                        title: Mode
                        type: string
                        enum:
                        - proxy
                        - ssh
                        x-walrus-ui:
                          order: 1
                      secret:
                        description: |
                          Specify the secret for connecting to proxy, either password or private key.
                        nullable: true
                        title: Secret
                        format: password
                        writeOnly: true
                        type: string
                        x-walrus-ui:
                          order: 3
                          widget: TextArea
                      user:
                        description: |
                          Specify the user for connecting to proxy.
                        nullable: true
                        title: User
                        type: string
                        x-walrus-ui:
                          order: 2
                    title: Authn
                    required:
                    - mode
                    type: object
                    x-walrus-ui:
                      colSpan: 12
                      order: 3
                  insecure:
                    description: |
                      Specify whether to skip TLS/Hostname verification when connecting to proxy.
                    default: false
                    nullable: true
                    title: Insecure
                    type: boolean
                    x-walrus-ui:
                      order: 2
                required:
                - address
                - authn
                type: object
                x-walrus-ui:
                  colSpan: 12
              title: Proxies
              type: array
              x-walrus-ui:
                colSpan: 12
                order: 4
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 5
        artifact:
          title: Artifact
          type: object
          description: |
            Specify the artifact of deployment, like a docker image, a war file and so on.
          required:
          - runtime_class
          - refer
          properties:
            command:
              description: |
                Specify the command to execute.
              title: Command
              type: string
              nullable: true
              x-walrus-ui:
                order: 3
            envs:
              description: |
                Specify the environment variables.
              nullable: true
              additionalProperties:
                type: string
              title: Envs
              type: object
              x-walrus-ui:
                colSpan: 12
                order: 4
            ports:
              description: |
                Specify the ports.
              nullable: true
              items:
                type: number
              title: Ports
              type: array
              x-walrus-ui:
                colSpan: 12
                order: 5
            refer:
              properties:
                authn:
                  description: |
                    Specify the authentication information for pulling artifact.
                  nullable: true
                  properties:
                    mode:
                      description: |
                        Specify the authentication mode for pulling artifact, select from none, basic or bearer.
                      default: none
                      title: Mode
                      type: string
                      enum:
                      - none
                      - bearer
                      - basic
                      x-walrus-ui:
                        order: 1
                    secret:
                      description: |
                        Specify the secret for pulling artifact, either password or token.
                      title: Secret
                      type: string
                      format: password
                      writeOnly: true
                      x-walrus-ui:
                        order: 3
                        showIf: mode!=none
                        widget: TextArea
                    user:
                      description: |
                        Specify the user for pulling artifact.
                      nullable: true
                      title: User
                      type: string
                      x-walrus-ui:
                        order: 2
                        showIf: mode=basic
                  required:
                  - mode
                  title: Authn
                  type: object
                  x-walrus-ui:
                    colSpan: 12
                    order: 3
                insecure:
                  description: |
                    Specify whether to skip TLS/Hostname verification when pulling artifact.
                  default: false
                  nullable: true
                  title: Insecure
                  type: boolean
                  x-walrus-ui:
                    order: 2
                uri:
                  title: Uri
                  type: string
                  x-walrus-ui:
                    order: 1
              required:
              - uri
              title: Refer
              type: object
              x-walrus-ui:
                colSpan: 12
                order: 2
            runtime_class:
              description: |
                Specify the runtime class for deploying.
                The supported classes are determined by the corresponding runtime source.
                See builtin runtime source for more details, https://github.com/seal-io/terraform-provider-courier/tree/main/pkg/runtime/source_builtin.
              default: tomcat
              title: Runtime Class
              type: string
              enum:
              - tomcat
              - docker
              - openjdk
              x-walrus-ui:
                colSpan: 12
                order: 1
            volumes:
              description: |
                Specify the volumes.
              nullable: true
              items:
                type: string
              title: Volumes
              type: array
              x-walrus-ui:
                colSpan: 12
                order: 6
                showIf: runtime_class=docker
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 4
      x-walrus-ui:
        groupOrder:
        - Basic
        - Advanced
